core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('registration/', views.user_registration, name='registration'),
    path('logout/', views.user_logout, name='logout'),

    path('statistics/', views.StatisticsView.as_view(), name='statistics'),

    path('test/', views.TestListView.as_view(), name='test'),
    path('test/<int:pk>', views.TestPassView.as_view(), name='test-pass'),
    path('test/<int:test_id>/question/<int:question_id>', views.question_view, name='question'),

    path('marketplace/' , views.MarketplaceView.as_view(), name='marketplace'),
    path('marketplace/<int:pk>', views.frame_view, name='frame'),
    path('my_frames/', views.MyFramesView.as_view(), name='my-frames'),
    path('my_frames/<int:pk>', views.my_frame_view, name='my-frame')
]

poll_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import Prefetch
from django.contrib.auth.password_validation import validate_password


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff=False, is_superuser=False, **other_fields):
        if not email:
            raise ValueError('Email address must be specified')

        if not password:
            raise ValueError('Password must be specified')

        user = self.model(
                    email=self.normalize_email(email),
                    is_staff=is_staff,
                    is_superuser=is_superuser,
                    **other_fields
                )
        validate_password(password)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password, **other_fields):
        return self._create_user(email, password, False, False, **other_fields)

    def create_superuser(self, email, password, **other_fields):
        return self._create_user(email, password, True, True, **other_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name="email address",
        max_length=256,
        unique=True)
    account = models.IntegerField(default=0)

    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'

    objects = CustomUserManager()

    @staticmethod
    def prefetch(q):
        q = q.prefetch_related(Prefetch('usertest_set', queryset=UserTest.objects.order_by('passed')))
        q = q.prefetch_related(Prefetch('userframe_set', queryset=UserFrame.objects.filter(active=True)))
        return q


class Test(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return f"{self.name}"

    @staticmethod
    def prefetch(q):
        q = q.prefetch_related(Prefetch('question_set', queryset=Question.objects.order_by('order')))
        return q


class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    answer = models.CharField(max_length=256)
    order = models.IntegerField()

    def __str__(self):
        return f"{self.text}"


class UserTest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    result = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)


class Frame(models.Model):
    TYPES = [
        ('login', 'login'),
        ('background', 'background'),
    ]
    color = models.CharField(max_length=256)
    price = models.IntegerField(default=0)
    type = models.CharField(max_length=256, choices=TYPES)

    def __str__(self):
        return f"{self.type}: {self.color}"


class UserFrame(models.Model):
    frame = models.ForeignKey(Frame, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=False)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "base.css" %}" rel="stylesheet">
    <link href="{% static "login.css" %}" rel="stylesheet">
    <link href="{% static "content.css" %}" rel="stylesheet">
    <link href="{% static "statistic.css" %}" rel="stylesheet">
</head>
<body style="background-color: {{ request.session.background_color }}">
{% if user.email %}
<div class="header">
    <a class="active" href="{% url 'test' %}">Test</a>
    <a href="{% url 'my-frames' %}">My frames</a>
    <a href="{% url 'marketplace' %}">Marketplace</a>
    <a href="{% url 'statistics' %}">Statistics</a>
    <div class="header-right" style="background-color: {{ request.session.login_color }}">
        <a class="active" href="{% url 'logout' %}">Logout</a>
        <table>
            <tr>
                <td>User:</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>Balance:</td>
                <td>{{ user.account }}</td>
            </tr>
        </table>
    </div>
</div>
{% endif %}
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}
{% block content %}
    <div class="authorization">
        <div class="authorization-box">
            <h1>Log-in</h1>
            <p>Please, use the following form to log-in:</p>
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                {% if login_error %}
                    <p style="color: red">Invalid login</p>
                {% endif %}
                <p><input class="grey-button" type="submit" value="Log-in"></p>
            </form>
            <a href="{% url 'registration' %}">Registration </a>
        </div>
    </div>
{% endblock %}

templates/marketplace.html
{% extends "base.html" %}

{% block title %}Marketplace{% endblock %}
{% block content %}
    <h1>Marketplace</h1>
    <div class="cards-group">
        {% if frame_list %}
        {% for frame in frame_list %}
        <div class="card">
            <div class="card-shadow">
                <form action="{% url 'frame' frame.id %}" method="post">
                    <div style="width: 200px; height: 200px; background-color: {{ frame.color }}"></div>
                    {% csrf_token %}
                    <div class="card-content">
                        <p>Type: {{ frame.type }}</p>
                        <p>Price: {{ frame.price }}</p>
                    </div>
                    <div class="card-button">
                        <input class="blue-button" type="submit" value="Buy">
                    </div>
                    {% if is_exist and frame.id == frame_id %}
                        <p style="padding: 10px; color: red; font-weight: normal">You already have this frame</p>
                    {% endif %}
                    {% if not_enough and frame.id == frame_id %}
                        <p style="padding: 10px; color: red; font-weight: normal">Not enough funds</p>
                    {% endif %}
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
            <p>No frame</p>
        {% endif %}
    </div>
{% endblock %}

templates/my_frames.html
{% extends "base.html" %}

{% block title %}My frames{% endblock %}
{% block content %}
    <h1>My frames</h1>
    <div class="cards-group">
        {% if frames %}
        {% for frame in frames %}
        <div class="card">
            <div class="card-shadow">
                <form action="{% url 'my-frame' frame.frame.id %}" method="post">
                    {% csrf_token %}
                    <div style="background-color: {{ frame.frame.color }};width: 200px;height: 200px"></div>
                    <div class="card-content">
                        <p>Type: {{ frame.frame.type }}</p>
                        <p>Price: {{ frame.frame.price }}</p>
                        <p>Status: {{ frame.active }}</p>
                    </div>
                    <div class="card-button">
                        <input class="blue-button" type="submit" value="Activate">
                    </div>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
            <p>No frame</p>
        {% endif %}
    </div>
{% endblock %}

templates/passing_test.html
{% extends "base.html" %}

{% block title %}Passing tests{% endblock %}
{% block content %}
    <h1>{{ test.name }}</h1>
    <p>Click the start button to run the test</p>
    <a class="blue-button" href="{% url 'question' test.id question.id %}">Start</a>
{% endblock %}

templates/question.html
{% extends "base.html" %}

{% block title %}Question{% endblock %}
{% block content %}
    <form action="{% url 'question' form.test.id form.question.id %}" method="post">
        <h3>{{ form.question }}</h3>
        {{ form.as_p }}
        {% csrf_token %}
        <input class="blue-button" type="submit" value="Next">
    </form>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}
{% block content %}
    <div class="authorization">
        <div class="authorization-box">
            <h1>Registration</h1>
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                {% if register_error %}
                    <p style="color: red">Invalid login</p>
                {% endif %}
                <p><input class="grey-button" type="submit" value="Registration"></p>
            </form>
            <a href="{% url 'login' %}">Log-in </a>
        </div>
    </div>
{% endblock %}

templates/statistics.html
{% extends "base.html" %}

{% block title %}Statistics{% endblock %}
{% block content %}
    <h1>Statistics</h1>
    {% if users %}
    <div class="statistic">
        <table>
        <tr>
            <th>Email</th>
            <th>Completed tests</th>
            <th>Color differentiation</th>
        </tr>
        {% for user in users %}
            <tr>
                <td>
                    <p>{{ user.email }}</p>
                </td>
                <td>
                    <p>{{ user.test_count }}</p>
                </td>
                {% if user.userframe_set %}
                <td>
                    {% for frame in user.userframe_set.all %}
                        <p>{{ frame.frame.type }}:</p>
                        <div style="height: 50px; height: 50px; background-color: {{ frame.frame.color }};"></div>
                    {% endfor %}
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
    </div>
    {% else %}
        <p>No frame</p>
    {% endif %}
{% endblock %}

templates/tests.html
{% extends "base.html" %}

{% block title %}Tests{% endblock %}
{% block content %}
    <h1>Test List</h1>
    {% if test_list %}
    <ul>
        {% for test in test_list %}
            <li>
                <a href="{% url 'test-pass' test.id %}">{{ test.name }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No tests</p>
    {% endif %}
{% endblock %}